library(markdown)
library(shiny)
shinyUI(fluidPage(
  titlePanel("Upload of Data and Information about Regression Model of GE stock versus S&P 500 for period 2004-2014"),
  sidebarLayout(
    sidebarPanel(
      fileInput('file1', 'Choose file to upload',
                accept = c(
                  'text/csv',
                  'text/comma-separated-values',
                  'text/tab-separated-values',
                  'text/plain',
                  '.csv',
                  '.tsv'
                )
      ),
      tags$hr(),
      checkboxInput('header', 'Header', TRUE),
      radioButtons('sep', 'Separator',
                   c(Comma=',',
                     Semicolon=';',
                     Tab='\t'),
                   ','),
      radioButtons('quote', 'Quote',
                   c(None='',
                     'Double Quote'='"',
                     'Single Quote'="'"),
                   '"'),
      tags$hr(),
      p(''
      )
    ),
    mainPanel(
      tableOutput('contenttable'),
      h4('Loading weather data'),
      textOutput('data_example_dim_one'),
      h4('number of rows in data frame'),
      textOutput('data_example_dim_two'),
      h4('number of columns in data frame'),
      textOutput('sumdataMeanTF'),
      h4('Data summary (Min - Q1 - Median - Mean - Q3 - Max) for Mean Temperature in Farenheit'),
      h4('Developing Linear Regression Model of GE versus S&P 500 2004-2014'),
      verbatimTextOutput('sum_lnadjcloseGE'),
      h4('Data summary (Min - Q1 - Median - Mean - Q3 - Max) for log return of GE'),
      verbatimTextOutput('sum_lnadjcloseSP500'),
      h4('Data summary (Min - Q1 - Median - Mean - Q3 - Max) for log return of S&P 500'),
      verbatimTextOutput('correlation_GESP500'),
      h4('Correlation coefficient between log return GE and S&P 500'),
      plotOutput('histlogGE'),
      h4('Histogram of GE log returns'),
      plotOutput('histlogSP500'),
      h4('Histogram of GE log returns'),
      textOutput('lmfitGEvsSP500estintercept'),
      h4('Estimate Intercept'),
      textOutput('lmfitGEvsSP500stderintercept'),
      h4('Standard Error Intercept'),
      textOutput('lmfitGEvsSP500tvalintercept'),
      h4('t-Statistic Intercept'),
      textOutput('lmfitGEvsSP500pvalintercept'),
      h4('P-value Intercept'),
      textOutput('lmfitGEvsSP500estslope'),
      h4('Estimate Slope'),
      textOutput('lmfitGEvsSP500stderslope'),
      h4('Standard Error Slope'),
      textOutput('lmfitGEvsSP500tvalslope'),
      h4('t-Statistic Slope'),
      textOutput('lmfitGEvsSP500pvalslope'),
      h4('P-value Slope'),
      textOutput('lmfitGEvsSP500resstderror'),
      h4('Residual Standard Error'),
      textOutput('lmfitGEvsSP500rsquared'),
      h4('R-squared of Model'),
      textOutput('lmfitGEvsSP500fstatistic'),
      h4('F-statistic - Number of degrees of freedom of Model'),
      verbatimTextOutput('lmfitGEvsSP500Residuals'),
      h4('Data summary (Min - Q1 - Median - Mean - Q3 - Max) for residuals'),
      textOutput('lmfitGEvsSP500anova'),
      h4('ANOVA Information for linear regression Model'),
      plotOutput('scatterGESP500'),
      h4('Scatterplot of data with regression line'),
      plotOutput('scatterresidualsvspredicted'),
      h4('Scatterplot of residuals versus predicted values')
    )
  )
))